import json
from fpdf import FPDF
import math

class StudyGuidePDF(FPDF):
    def __init__(self, subject: str, theme: dict):
        super().__init__(orientation="L", unit="mm", format="A4")
        self.subject = subject
        self.theme = theme
        self.set_auto_page_break(auto=True, margin=15)
        self.set_margins(10, 10, 10)
        self.col_widths = [12, 12, 55, 95, 18, 18, 25, 25]

    def add_page(self, *args, **kwargs):
        super().add_page(*args, **kwargs)
        self.set_fill_color(*self.theme["paper_bg"])
        self.rect(0, 0, self.w, self.h, "F")

theme = {
    "bg": (240, 240, 240),
    "accent": (100, 100, 100),
    "text": (0, 0, 0),
    "subtext": (100, 100, 100),
    "paper_bg": (255, 255, 255),
    "paper_text": (0, 0, 0),
    "paper_border": (200, 200, 200),
    "font_family": "helvetica"
}

pdf = StudyGuidePDF("TEST SUBJECT", theme)

# --- Magazine-Style Cover Page ---
pdf.add_page()
pdf.set_fill_color(*theme["bg"])
pdf.rect(0, 0, pdf.w, pdf.h, "F")

pdf.set_fill_color(*theme["accent"])
pdf.rect(15, 0, 8, pdf.h, "F")

cx, cy = pdf.w / 2 + 5, pdf.h / 2 + 10
pdf.set_draw_color(*theme["accent"])
pdf.set_line_width(1.5)
pdf.ellipse(cx - 30, cy - 30, 60, 60, "D")
pdf.set_fill_color(*theme.get("primary", (40, 40, 40)))
pdf.ellipse(cx - 10, cy + 10, 40, 40, "F")
pdf.line(15, cy - 40, pdf.w, cy - 40)
pdf.line(cx + 10, cy + 50, cx + 10, pdf.h)

pdf.set_y(40)
pdf.set_x(30)
pdf.set_font(theme["font_family"], "B", 42)
pdf.set_text_color(*theme["text"])
pdf.multi_cell(0, 16, "TEST SUBJECT LONG", align="L")

pdf.set_x(30)
pdf.set_font(theme["font_family"], "", 14)
pdf.set_text_color(*theme["subtext"])
pdf.cell(0, 10, f"CURATED FOR: AUTHOR", align="L", ln=True)

pdf.set_y(pdf.h - 30)
pdf.set_x(30)
pdf.set_font(theme["font_family"], "I", 10)
pdf.set_text_color(*theme["subtext"])
pdf.cell(0, 10, "Generated by Play2PDF Studio", align="L")

# --- Study Grid Page ---
pdf.add_page()
pdf.set_draw_color(*theme["paper_border"])
pdf.set_text_color(*theme["paper_text"])
pdf.set_font(theme["font_family"], "B", 10)
pdf.cell(0, 8, "SUMMARY", align="C", fill=True, ln=True)
pdf.ln(4)

# render headers
def render_headers(pdf):
    CW = pdf.col_widths
    pdf.cell(CW[0], 8, "[ ]", border="TB", align="C")
    pdf.cell(CW[1], 8, "#", border="TB", align="C")
    pdf.cell(CW[2], 8, "Topic", border="TB")
    pdf.cell(CW[3], 8, "Video", border="TB", ln=True)

render_headers(pdf)

CW = pdf.col_widths
for i in range(15):
    row_height = 20
    if pdf.will_page_break(row_height + 4):
        pdf.add_page()
        render_headers(pdf)

    row_y = pdf.get_y()
    pdf.set_xy(10, row_y)
    pdf.cell(CW[0], row_height, "[  ]", border="B", align="C")
    pdf.cell(CW[1], row_height, str(i), border="B", align="C")
    pdf.cell(CW[2], row_height, "Topic " + str(i), border="B")
    pdf.cell(CW[3], row_height, "Video " + str(i), border="B", ln=True)

pdf.output("test2.pdf")
print("PDF created with", pdf.page_no(), "pages")
