package com.adnanfoisal.play2pdf.ui.compile.components

import androidx.compose.ui.graphics.Color
import com.adnanfoisal.play2pdf.data.repository.ServerThemePalettes
import com.adnanfoisal.play2pdf.domain.model.PdfTheme

/**
 * Colour palette for each backend PDF theme, used by the in-app mini
 * "page" previews.
 *
 * GENERATED by scripts/gen_theme_palettes.py from backend/server.py's
 * THEMES dict — do not hand-edit; re-run the script after changing a
 * theme server-side. At runtime, [com.adnanfoisal.play2pdf.data.repository.ServerThemePalettes]
 * (fed by GET /themes) takes precedence; these values are the
 * always-correct offline fallback.
 *
 * Two surfaces, because every PDF has both:
 *  - cover*  the editorial cover page (bg / text / subtext)
 *  - page*   the study-grid page (paper_bg / paper_text / paper_border)
 *  - accent  shared accent (cover geometry + page links/headers)
 */
data class PdfThemePalette(
    val coverBg: Color,
    val coverText: Color,
    val coverSubtext: Color,
    val pageBg: Color,
    val pageText: Color,
    val pageBorder: Color,
    val accent: Color,
    val serif: Boolean,
    val fontName: String
)

fun PdfTheme.palette(): PdfThemePalette {
    // Live server palettes (GET /themes) take precedence when loaded.
    ServerThemePalettes.byApiName[apiName]?.let { return it }
    return localFallback()
}

private fun PdfTheme.localFallback(): PdfThemePalette = when (this) {
    PdfTheme.NordicFrost -> PdfThemePalette(
        coverBg = Color(0xFFF2F6FA), coverText = Color(0xFF2C3E50), coverSubtext = Color(0xFF7F8C8D),
        pageBg = Color(0xFFFFFFFF), pageText = Color(0xFF2C3E50), pageBorder = Color(0xFFECF0F1),
        accent = Color(0xFF86A8C4), serif = true, fontName = "Times"
    )
    PdfTheme.VelvetDawn -> PdfThemePalette(
        coverBg = Color(0xFFFDF6F1), coverText = Color(0xFF5C4646), coverSubtext = Color(0xFFA89090),
        pageBg = Color(0xFFFFFCF9), pageText = Color(0xFF5C4646), pageBorder = Color(0xFFF5EBE6),
        accent = Color(0xFFD69E91), serif = true, fontName = "Times"
    )
    PdfTheme.MintBlueprint -> PdfThemePalette(
        coverBg = Color(0xFFEDFCF8), coverText = Color(0xFF0F766E), coverSubtext = Color(0xFF14B8A6),
        pageBg = Color(0xFFFFFFFF), pageText = Color(0xFF0F766E), pageBorder = Color(0xFFCCFBF1),
        accent = Color(0xFF34D399), serif = false, fontName = "Courier"
    )
    PdfTheme.GoldenEra -> PdfThemePalette(
        coverBg = Color(0xFFF4F0E6), coverText = Color(0xFF423426), coverSubtext = Color(0xFF756658),
        pageBg = Color(0xFFFCFAF5), pageText = Color(0xFF423426), pageBorder = Color(0xFFDED3BE),
        accent = Color(0xFFB8914E), serif = true, fontName = "Times"
    )
    PdfTheme.MidnightPurple -> PdfThemePalette(
        coverBg = Color(0xFF140F26), coverText = Color(0xFFFFFFFF), coverSubtext = Color(0xFFB4A8CC),
        pageBg = Color(0xFF1E1833), pageText = Color(0xFFF0F0F0), pageBorder = Color(0xFF453A64),
        accent = Color(0xFFFF2A80), serif = false, fontName = "Helvetica"
    )
    PdfTheme.Cyberpunk2077 -> PdfThemePalette(
        coverBg = Color(0xFF121212), coverText = Color(0xFFFAFA33), coverSubtext = Color(0xFF8C8C8C),
        pageBg = Color(0xFF1C1C1C), pageText = Color(0xFFE6E6E6), pageBorder = Color(0xFF333333),
        accent = Color(0xFF00FFF0), serif = false, fontName = "Courier"
    )
    PdfTheme.ObsidianCrimson -> PdfThemePalette(
        coverBg = Color(0xFF0A0A0A), coverText = Color(0xFFE0E0E0), coverSubtext = Color(0xFF808080),
        pageBg = Color(0xFF121212), pageText = Color(0xFFC8C8C8), pageBorder = Color(0xFF282828),
        accent = Color(0xFFDC143C), serif = false, fontName = "Helvetica"
    )
    PdfTheme.OceanicAbyss -> PdfThemePalette(
        coverBg = Color(0xFF040F1F), coverText = Color(0xFFF0F8FF), coverSubtext = Color(0xFF6495ED),
        pageBg = Color(0xFF0A192F), pageText = Color(0xFFDCEBFF), pageBorder = Color(0xFF1E3A8A),
        accent = Color(0xFF00CCFF), serif = false, fontName = "Helvetica"
    )
    PdfTheme.TufteScholar -> PdfThemePalette(
        coverBg = Color(0xFFFAF8F5), coverText = Color(0xFF1F1F1F), coverSubtext = Color(0xFF646464),
        pageBg = Color(0xFFFAF8F5), pageText = Color(0xFF1F1F1F), pageBorder = Color(0xFFDCD7CD),
        accent = Color(0xFFB59A57), serif = true, fontName = "Times"
    )
    PdfTheme.PrincetonMath -> PdfThemePalette(
        coverBg = Color(0xFF1E3A8A), coverText = Color(0xFFFFFFFF), coverSubtext = Color(0xFFC8C8C8),
        pageBg = Color(0xFFFFFFFC), pageText = Color(0xFF1E293B), pageBorder = Color(0xFFCBD5E1),
        accent = Color(0xFFF97316), serif = true, fontName = "Times"
    )
    PdfTheme.MidnightTerminal -> PdfThemePalette(
        coverBg = Color(0xFF000000), coverText = Color(0xFF00F0FF), coverSubtext = Color(0xFF009696),
        pageBg = Color(0xFF000000), pageText = Color(0xFF39FF14), pageBorder = Color(0xFF00F0FF),
        accent = Color(0xFF39FF14), serif = false, fontName = "Courier"
    )
    PdfTheme.CambridgeEmerald -> PdfThemePalette(
        coverBg = Color(0xFF0F4C3A), coverText = Color(0xFFFEFDF9), coverSubtext = Color(0xFF969696),
        pageBg = Color(0xFFFEFDF9), pageText = Color(0xFF0F4C3A), pageBorder = Color(0xFFD4AF37),
        accent = Color(0xFFD4AF37), serif = true, fontName = "Times"
    )
    PdfTheme.BauhausGeometric -> PdfThemePalette(
        coverBg = Color(0xFFF4F1EA), coverText = Color(0xFF000000), coverSubtext = Color(0xFF646464),
        pageBg = Color(0xFFF4F1EA), pageText = Color(0xFF000000), pageBorder = Color(0xFF000000),
        accent = Color(0xFFE65F2B), serif = false, fontName = "Helvetica"
    )
    PdfTheme.SwissStark -> PdfThemePalette(
        coverBg = Color(0xFF000000), coverText = Color(0xFFFFFFFF), coverSubtext = Color(0xFF969696),
        pageBg = Color(0xFFFFFFFF), pageText = Color(0xFF000000), pageBorder = Color(0xFFE2E8F0),
        accent = Color(0xFFDC2626), serif = false, fontName = "Helvetica"
    )
    PdfTheme.OxfordBurgundy -> PdfThemePalette(
        coverBg = Color(0xFF701A25), coverText = Color(0xFFFDFBF7), coverSubtext = Color(0xFF969696),
        pageBg = Color(0xFFFDFBF7), pageText = Color(0xFF701A25), pageBorder = Color(0xFFDCCDC8),
        accent = Color(0xFFF59E0B), serif = true, fontName = "Times"
    )
    PdfTheme.DeepSpace -> PdfThemePalette(
        coverBg = Color(0xFF0B0F19), coverText = Color(0xFF8B5CF6), coverSubtext = Color(0xFF646496),
        pageBg = Color(0xFF0B0F19), pageText = Color(0xFFFFFFFF), pageBorder = Color(0xFF8B5CF6),
        accent = Color(0xFF06B6D4), serif = false, fontName = "Helvetica"
    )
    PdfTheme.MitTech -> PdfThemePalette(
        coverBg = Color(0xFF0D9488), coverText = Color(0xFFFFFFFF), coverSubtext = Color(0xFFC8C8C8),
        pageBg = Color(0xFFFFFFFF), pageText = Color(0xFF343A42), pageBorder = Color(0xFFCBD5E1),
        accent = Color(0xFF6B7280), serif = false, fontName = "Helvetica"
    )
    PdfTheme.WhartonLedger -> PdfThemePalette(
        coverBg = Color(0xFF0F172A), coverText = Color(0xFFFFFFFF), coverSubtext = Color(0xFF969696),
        pageBg = Color(0xFFFFFFFF), pageText = Color(0xFF0F172A), pageBorder = Color(0xFFE2E8F0),
        accent = Color(0xFF47556B), serif = true, fontName = "Times"
    )
    PdfTheme.SumiInk -> PdfThemePalette(
        coverBg = Color(0xFFFAFAFA), coverText = Color(0xFF2B2B2B), coverSubtext = Color(0xFF646464),
        pageBg = Color(0xFFFAFAFA), pageText = Color(0xFF2B2B2B), pageBorder = Color(0xFFE5E5E5),
        accent = Color(0xFFC2410C), serif = true, fontName = "Times"
    )
    PdfTheme.RenaissanceGold -> PdfThemePalette(
        coverBg = Color(0xFF4E3629), coverText = Color(0xFFF3EFE0), coverSubtext = Color(0xFF969696),
        pageBg = Color(0xFFF3EFE0), pageText = Color(0xFF4E3629), pageBorder = Color(0xFFC5A059),
        accent = Color(0xFFC5A059), serif = true, fontName = "Times"
    )
    PdfTheme.WarmSunsetDark -> PdfThemePalette(
        coverBg = Color(0xFF1E1514), coverText = Color(0xFFE8E6E3), coverSubtext = Color(0xFF969696),
        pageBg = Color(0xFF221B19), pageText = Color(0xFFE8E6E3), pageBorder = Color(0xFFC55A67),
        accent = Color(0xFFFF9E64), serif = false, fontName = "Helvetica"
    )
}
