"""
Regenerates PdfThemePalette.kt from the backend's authoritative THEMES dict.

The in-app PDF theme previews were hand-tuned and drifted from reality on
11 of 21 themes. This script makes drift impossible: the Kotlin fallback
palettes are GENERATED from backend/server.py.

Run from anywhere:  python scripts/gen_theme_palettes.py
(uses backend/server.py on sys.path; no network needed)
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "backend"))

from server import THEMES  # noqa: E402

OUT = os.path.join(
    ROOT,
    "app/src/main/java/com/adnanfoisal/play2pdf/ui/compile/components/PdfThemePalette.kt",
)


def pascal(api: str) -> str:
    # nordic_frost -> NordicFrost, cyberpunk_2077 -> Cyberpunk2077
    return "".join(p.capitalize() for p in api.split("_"))


def hex_of(rgb: tuple) -> str:
    return "0xFF%02X%02X%02X" % rgb


HEADER = """package com.adnanfoisal.play2pdf.ui.compile.components

import androidx.compose.ui.graphics.Color
import com.adnanfoisal.play2pdf.data.repository.ServerThemePalettes
import com.adnanfoisal.play2pdf.domain.model.PdfTheme

/**
 * Colour palette for each backend PDF theme, used by the in-app mini
 * "page" previews.
 *
 * GENERATED by scripts/gen_theme_palettes.py from backend/server.py's
 * THEMES dict — do not hand-edit; re-run the script after changing a
 * theme server-side. At runtime, [com.adnanfoisal.play2pdf.data.repository.ServerThemePalettes]
 * (fed by GET /themes) takes precedence; these values are the
 * always-correct offline fallback.
 *
 * Two surfaces, because every PDF has both:
 *  - cover*  the editorial cover page (bg / text / subtext)
 *  - page*   the study-grid page (paper_bg / paper_text / paper_border)
 *  - accent  shared accent (cover geometry + page links/headers)
 */
data class PdfThemePalette(
    val coverBg: Color,
    val coverText: Color,
    val coverSubtext: Color,
    val pageBg: Color,
    val pageText: Color,
    val pageBorder: Color,
    val accent: Color,
    val serif: Boolean,
    val fontName: String
)

fun PdfTheme.palette(): PdfThemePalette {
    // Live server palettes (GET /themes) take precedence when loaded.
    ServerThemePalettes.byApiName[apiName]?.let { return it }
    return localFallback()
}

private fun PdfTheme.localFallback(): PdfThemePalette = when (this) {
"""

FOOTER = """}
"""


def main():
    lines = [HEADER]
    for api, t in THEMES.items():
        enum = pascal(api)
        serif = t["font_family"] == "Times"
        lines.append(
            f"""    PdfTheme.{enum} -> PdfThemePalette(
        coverBg = Color({hex_of(t['bg'])}), coverText = Color({hex_of(t['text'])}), coverSubtext = Color({hex_of(t['subtext'])}),
        pageBg = Color({hex_of(t['paper_bg'])}), pageText = Color({hex_of(t['paper_text'])}), pageBorder = Color({hex_of(t['paper_border'])}),
        accent = Color({hex_of(t['accent'])}), serif = {"true" if serif else "false"}, fontName = "{t['font_family']}"
    )
"""
        )
    lines.append("}\n")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("".join(lines))
    print(f"wrote {OUT} with {len(THEMES)} themes")


if __name__ == "__main__":
    main()
